# -*- coding: utf-8 -*-
"""TASK-2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HJn3zg5dlOrhHBZdImnDD4K0nkmPLrC3
"""

import random
import string

def generate_password(length):
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for _ in range(length))
    return password

def password_generator():
    print("Password Generator")

    try:
        length = int(input("Enter the desired length of the password: "))
    except ValueError:
        print("Invalid input. Please enter a valid number.")
        return

    if length <= 0:
        print("Invalid length. Please enter a positive number.")
        return

    password = generate_password(length)

    print(f"Generated Password: {password}")

# Run the password generator
password_generator()